### ISSUE TITLE
XOR gates are hard to see

### ISSUE THREAD

**Issue by vincentmacri** [TheVirtualMachine/AmazingMaze#18]
The XOR gates look too similar to the OR gates. The extra line which makes it an XOR should be more prominent.

**Comment by susie-son** [comment]
![xor-off](https://cloud.githubusercontent.com/assets/15661685/26281304/50e310f6-3dc1-11e7-8a99-4f9987a9bd44.png)
![xor-on](https://cloud.githubusercontent.com/assets/15661685/26281306/50ef8304-3dc1-11e7-9ae9-2c32069a2029.png)
![xor-unknown](https://cloud.githubusercontent.com/assets/15661685/26281305/50ee8a3a-3dc1-11e7-8549-11063cea6850.png)

**Comment by vincentmacri** [comment]
@susie-son It's mostly the colour that makes it hard to see, especially with the unknown state. Increasing the thickness helps, but doesn't fix it. Use a colour that contrasts more with the grey background, or change the background colour.

**Comment by susie-son** [comment]
![xor-off](https://cloud.githubusercontent.com/assets/15661685/26369073/932f5350-3fc1-11e7-90a1-296914883e5c.png)
![xor-on](https://cloud.githubusercontent.com/assets/15661685/26369074/9336e3e0-3fc1-11e7-988c-95745bab245c.png)
![xor-unknown](https://cloud.githubusercontent.com/assets/15661685/26369075/934eb60a-3fc1-11e7-9eb5-0772bdeee956.png)
